#!/usr/bin/python2

import argparse
import re
import sqlite3

def main(database,expression):
    match_list  = []
    regex_match = re.compile(expression,re.VERBOSE|re.IGNORECASE)
    db = sqlite3.connect(database)
    cursor = db.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
    tables = cursor.fetchall()
    for table in tables:
        print "[*] Scanning table...%s" % table
        cursor.execute("SELECT * FROM %s" % table[0])
        rows = cursor.fetchall()
        for row in rows:
            for column in row:
                try:
                    matches = regex_match.findall(column)
                except:
                    continue
                for match in matches:
                    match_list.append((match,table[0],column))

    cursor.close()
    db.close()
    print "[*] Discovered %d matches." % len(match_list)
 
    for match in match_list:
        print match

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("-d","--database", required=True,help="Path to the SQLite database you wish to analyze.")
    ap.add_argument("-e","--expression", required=True,help="Regex expression to match.")
    args = vars(ap.parse_args())
    main(args['database'],args['expression'])
